[package]
name = "mastermind"
version = "0.1.0"
authors = ["Raclett3 <im@s283.net>"]
edition = "2018"

[lib]
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.9.0"
